spring:
  application:
    name: UniVendas
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uni_vendas?useTimezone=true&serverTimezone=UTC
    hikari:
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
logging:
  level:
    #com.kawevk: DEBUG
    root: info